### ISSUE TITLE
help with setting up Stackdriver application credentials

### ISSUE THREAD

**Issue by moooofly** [census-instrumentation/opencensus-service#112]
After https://github.com/census-instrumentation/opencensus-service/commit/86437e9ee6106dd399cad7b7ba4e7391ad68c36f , I have a try with `opencensus-service`

with default `config.yaml`

```
[#213#root@ubuntu-1604 /go/src/github.com/census-instrumentation/opencensus-service]$cat cmd/ocagent/config.yaml
opencensus_interceptor:
  address: "127.0.0.1:55678"

stackdriver:
  project: "project-id"
  enable_tracing: true

zipkin:
  endpoint: "http://localhost:9411/api/v2/spans"
[#214#root@ubuntu-1604 /go/src/github.com/census-instrumentation/opencensus-service]$
```

I get

```
[#214#root@ubuntu-1604 /go/src/github.com/census-instrumentation/opencensus-service]$./bin/ocagent_linux -c cmd/ocagent/config.yaml
2018/10/18 14:49:15 Failed to create config for "stackdriver": Cannot configure Stackdriver Trace exporter: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
[#215#root@ubuntu-1604 /go/src/github.com/census-instrumentation/opencensus-service]$
```

As codes between [stackdriver.go#L209](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/857ff689ec3b8d8ebb64827938f1ff602eee59a9/stackdriver.go#L209) and [stackdriver.go#L218](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/857ff689ec3b8d8ebb64827938f1ff602eee59a9/stackdriver.go#L218) shows, if and only if `o.ProjectID == ""`, can obtain default credentials by `google.FindDefaultCredentials(xxx)`

```golang
	if o.ProjectID == "" {
		creds, err := google.FindDefaultCredentials(o.Context, traceapi.DefaultAuthScopes()...)
		if err != nil {
			return nil, fmt.Errorf("stackdriver: %v", err)
		}
		if creds.ProjectID == "" {
			return nil, errors.New("stackdriver: no project found with application default credentials")
		}
		o.ProjectID = creds.ProjectID
	}
```

and the error above actually comes from [here](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/857ff689ec3b8d8ebb64827938f1ff602eee59a9/stackdriver.go#L224)

```golang
	se, err := newStatsExporter(o)       // here
	if err != nil {
		return nil, err
	}
```

After some digging, find [this](https://github.com/google/web-bsd-hunt/blob/master/third_party/src/cloud.google.com/go/monitoring/apiv3/metric_client.go#L110)

```golang
func NewMetricClient(ctx context.Context, opts ...option.ClientOption) (*MetricClient, error) {
	conn, err := transport.DialGRPC(ctx, append(defaultMetricClientOptions(), opts...)...)    // here
	if err != nil {
		return nil, err
	}
	c := &MetricClient{
		conn:        conn,
		client:      monitoringpb.NewMetricServiceClient(conn),
		CallOptions: defaultMetricCallOptions(),
	}
	c.SetGoogleClientInfo("gax", gax.Version)
	return c, nil
```

from the codes below, I see credentials should be configured properly first, but it is not easy to find out as first run.

```
// FindDefaultCredentials searches for "Application Default Credentials".
//
// It looks for credentials in the following places,
// preferring the first location found:
//
//   1. A JSON file whose path is specified by the
//      GOOGLE_APPLICATION_CREDENTIALS environment variable.
//   2. A JSON file in a location known to the gcloud command-line tool.
//      On Windows, this is %APPDATA%/gcloud/application_default_credentials.json.
//      On other systems, $HOME/.config/gcloud/application_default_credentials.json.
//   3. On Google App Engine it uses the appengine.AccessToken function.
//   4. On Google Compute Engine and Google App Engine Managed VMs, it fetches
//      credentials from the metadata server.
//      (In this final case any provided scopes are ignored.)
func FindDefaultCredentials(ctx context.Context, scopes ...string) (*DefaultCredentials, error) {
    return findDefaultCredentials(ctx, scopes)
}
```

Need some advice, thanks in advance.

**Comment by odeke-em** [comment]
@moooofly thanks for the question. So if you see the configuration
```yaml
stackdriver:
    project: <project_here>
```

Please set your Google Stackdriver Project ID in there, so for example if it is "moooofly"
```yaml
stackdriver:
   project: moooofly
```
and ensure that your default application credentials by https://cloud.google.com/docs/authentication/production or even easier
if you have the credentials file set in your environment `GOOGLE_APPLICATION_CREDENTIALS`

For example this is how I run mine
```shell
GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/census-demos.json ./bin/ocagent_darwin --config cmd/ocagent/config.yaml 
```
where my `config.yaml` file is
```yaml
opencensus_interceptor:
  address: "127.0.0.1:55678"

stackdriver:
  project: "project-id"
  enable_tracing: true

zipkin:
  endpoint: "http://localhost:9411/api/v2/spans"
```

Hope this helps.
