### ISSUE TITLE
cmd/ocagent: allow configuration file to specify OpenCensus interceptor port

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-service#23]
The configuration file needs to be updated to support custom host:port to start the agent server .

```
listen: "localhost:777"

exporters:
    stackdriver:
        project: "project-id"
        enableTraces: true

    zipkin:
        endpoint: "http://localhost:9411/api/v2/spans"
```
