### ISSUE TITLE
cmd/ocagent: wrong Zipkin receiver vs exporter logical conflict detection

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#233]
Currently with a configuration such as
```yaml
receivers:
    zipkin:
        address: "localhost:9410"

exporters:
    zipkin:
        endpoint: "http://localhost:9411/api/v2/spans"
```

and then running either cmd/ocagent or cmd/occollector will result in
```shell
2018/11/26 18:40:53 Configuration logical error: ZipkinExporter address ("localhost:9411") aka (localhost on port 9411)
is the same as the receiver address ("localhost:9410") aka (localhost on port 9411)
```
which is clearly a wrong error "localhost:9410" is not "localhost:9411" but even worse

```shell
is the same as the receiver address ("localhost:9410") aka (localhost on port 9411)
```
Which is a consequence of a typographic error in https://github.com/census-instrumentation/opencensus-service/blob/5bd378023295ee43a9c6c0812a857d9022b7b7a6/cmd/ocagent/config.go#L186

which was reported by @pjanotti in PR https://github.com/census-instrumentation/opencensus-service/pull/229

I am filing this issue separately to make a focused fix and keep changes minimal and testable but to also allow for future regression isolation.

I'll mail a PR shortly.
