### ISSUE TITLE
cmd/ocagent: OpenCensus receiver gRPC server error for registering after (*grpc).Server.Serve

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#243]
Currently running ocagent with this YAML configuration
```yaml
receivers:
    opencensus:
        address: "127.0.0.1:55678"

exporters:
    zipkin:
        endpoint: "http://localhost:9411/api/v2/spans"
```
gives 
```shell
$ ./bin/ocagent_darwin --config t.yaml 
2018/12/03 00:29:12 Running OpenCensus Trace receiver as a gRPC service at "127.0.0.1:55678"
FATAL: 2018/12/03 00:29:12 grpc: Server.RegisterService after Server.Serve for "opencensus.proto.agent.metrics.v1.MetricsService"
```

where the error starts from

https://github.com/census-instrumentation/opencensus-service/blob/b093b60e9ad4929a2ed5b22f8fa5f0399af5b69e/cmd/ocagent/main.go#L174-L186

of which the root cause is that when invoking either of StartTraceReception or StartMetricsReception, we invoke .Serve on the gRPC server which requires that all services be registered before invoking .Serve.

### Proposed fix
Now I recall my previous train of thought, for which the fix should be:
a) If both trace and metrics are enabled, then invoke a Start method on the receiver that registers both services before finally invoking (*grpc.Server).Serve
b) Register either of those services and then finally a method that invokes (*grpc.Server).Serve
