### ISSUE TITLE
Golang OpenCensus Agent sample appears to not work

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-service#456]
https://opencensus.io/exporters/supported-exporters/go/ocagent/

With a configuration
```
receivers:
    opencensus:
        address: "127.0.0.1:55678"

exporters:
    datadog:
        namespace: ocagent
        enable_metrics: true
        enable_tracing: false
    prometheus:
        namespace: ocagent
        address: "localhost:9090"
    stackdriver:
        project: "dazwilkin-190221-trillian"
        metric_prefix: ocagent
        enable_metrics: true

zpages:
    port: 55679
```

The agent (!) appears to receive no data from the sample.

The agent isn't verbose (#453) but tweaking the configuration to use a Prometheus receiver and tweaking the sample to use the Prometheus exporter, works better (albeit imperfectly):
```
receivers:
    opencensus:
        address: "127.0.0.1:55678"
    prometheus:
      config:
        scrape_configs:
        - job_name: 'test'
          scrape_interval: 5s
          static_configs:
          - targets: ['localhost:8889']

exporters:
    datadog:
        namespace: ocagent
        enable_metrics: true
        enable_tracing: false
    prometheus:
        namespace: ocagent
        address: "localhost:9090"
    stackdriver:
        project: "dazwilkin-190221-trillian"
        metric_prefix: ocagent
        enable_metrics: true

zpages:
    port: 55679
```
and then
```
oce,err:=prometheus.NewExporter(prometheus.Options{
	Namespace: "ocagent",
})
if err != nil {
	log.Fatalf("Failed to create exporter: %v", err)
}
//trace.RegisterExporter(oce)
view.RegisterExporter(oce)

go func() {
	mux:=http.NewServeMux()
	mux.Handle("/metrics",oce)
	if err:=http.ListenAndServe(":8889",mux);err!=nil{
		log.Fatal(err)
	}
}()
```
**NB** retained `oce` for convenience.

I'm then able to curl the Prometheus exporter's metrics (`:9090/metrics`) which shows that the agent is proxying them from the receiver (`:8889/metrics`)
```
# HELP ocagent_ocagent_opdemo_latency The various latencies of the methods
# TYPE ocagent_ocagent_opdemo_latency histogram
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="10"} 0
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="50"} 1
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="100"} 8
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="200"} 12
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="400"} 14
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="800"} 16
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="1000"} 17
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="1400"} 17
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="2000"} 18
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="5000"} 19
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="10000"} 19
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="15000"} 39
ocagent_ocagent_opdemo_latency_bucket{client="cli",method="repl",le="+Inf"} 39
ocagent_ocagent_opdemo_latency_sum{client="cli",method="repl"} 20416.791576000163
ocagent_ocagent_opdemo_latency_count{client="cli",method="repl"} 39
# HELP ocagent_ocagent_opdemo_line_counts The counts of the lines in
# TYPE ocagent_ocagent_opdemo_line_counts counter
ocagent_ocagent_opdemo_line_counts{client="cli",method="repl"} 60
# HELP ocagent_ocagent_opdemo_line_lengths The lengths of the various lines in
# TYPE ocagent_ocagent_opdemo_line_lengths histogram
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="10"} 0
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="20"} 0
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="50"} 2
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="100"} 3
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="150"} 9
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="200"} 11
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="500"} 14
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="800"} 88
ocagent_ocagent_opdemo_line_lengths_bucket{client="cli",method="repl",le="+Inf"} 88
ocagent_ocagent_opdemo_line_lengths_sum{client="cli",method="repl"} 31003.999999999767
ocagent_ocagent_opdemo_line_lengths_count{client="cli",method="repl"} 88
# HELP ocagent_ocagent_opdemo_process_counts The various counts
# TYPE ocagent_ocagent_opdemo_process_counts counter
ocagent_ocagent_opdemo_process_counts{client="cli",method="repl"} 20
```
The Stackdriver Account receives the metrics (created) but no data is received:
```
GET https://monitoring.googleapis.com/v3/projects/[[REDACTED]]/metricDescriptors?filter=metric.type%3Dstarts_with(%22custom.googleapis.com%2Fopencensus%2Focagent%22)&fields=metricDescriptors%2FdisplayName&key={YOUR_API_KEY}
 
 
Response
 
200
 
- Show headers -
  
{
 "metricDescriptors": [
  {
   "displayName": "ocagent/ocagent_opdemo_latency"
  },
  {
   "displayName": "ocagent/ocagent_opdemo_line_counts"
  },
  {
   "displayName": "ocagent/ocagent_opdemo_line_lengths"
  },
  {
   "displayName": "ocagent/ocagent_opdemo_process_counts"
  }
 ]
}
```
The Datadog agent receives no data... I think the agent's Datadog metrics functionality is broken (#454)
