### ISSUE TITLE
application to ocagent to jaeger exporter loose service name

### ISSUE THREAD

**Issue by daeMOn63** [census-instrumentation/opencensus-service#568]
I have an application registering an ocagent exporter like so:
```
oce, err := ocagent.NewExporter(
		ocagent.WithInsecure(),
		ocagent.WithServiceName("my-app")
)
```
And this ocagent configuration:
```
receivers:
  opencensus:
    address: "0.0.0.0:55678"

exporters:
  jaeger:
    collector_endpoint: "http://jaeger:14268/api/traces"
```

When browsing to the jaeger interface, I'm expecting to see the service "my-app" being listed, but instead, I only have a default "Opencensus" service.

I managed to change the default service name by adding the service_name to the jaeger configuration:
```
receivers:
  opencensus:
    address: "0.0.0.0:55678"

exporters:
  jaeger:
    service_name: "my-app"
    collector_endpoint: "http://jaeger:14268/api/traces"
```

But I would prefer not having to do that, so I could have multiple applications exporting to the same agent, and still the jaeger UI display the service names as specified in the application.

Is there any way to achieve this ?
