### ISSUE TITLE
exporter/opencensus: No metrics supported

### ISSUE THREAD

**Issue by inigohu** [census-instrumentation/opencensus-service#599]
I'm using opencensus-agent exporter (golang client), to send data to an agent, then to a collector and finally to stackdriver.
I can see traces in stackdriver, but not metrics. I've also added a prometheus exporter in my service to check that I'm generating metrics correctly.
Here are my configs:

main.go
```go
oce, err := ocagent.NewExporter(
		ocagent.WithInsecure(),
		ocagent.WithReconnectionPeriod(5*time.Second),
		ocagent.WithAddress(ocAgentAddress),
		ocagent.WithServiceName("my-service"))
if err != nil {
	log.Fatalf("Failed to create a new ocagent exporter: %v", err)
}

trace.RegisterExporter(oce)
view.RegisterExporter(oce)
```
oc-agent-config.yaml
```yaml
receivers:
  opencensus:
    address: ":55678"

exporters:
  opencensus:
    endpoint: "oc-collector:55678"
```
oc-collector-config.yaml
```yaml
receivers:
  opencensus:
    port: 55678

exporters:
  stackdriver:
    project: "xxxxxxx"
    metric_prefix: "demo"
    enable_tracing: true
    enable_metrics: true
```
