### ISSUE TITLE
Official KairosDB exporter for metrics.

### ISSUE THREAD

**Issue by rcosnita** [census-instrumentation/opencensus-service#633]
It would be nice to have a KairosDB exporter which can be used explicitly in the agent. The exporter should be configured using a configuration similar to the one below:

```yaml
exporters:
    kairosdb:
        endpoint: "http://127.0.0.1:8080/api/v1/datapoints"
        log_level: debug
        log_consumed_metrics: false
        http:
            max_connections: 10 # the maximum number of concurrent connections opened to the kairosdb rest api.
            connection_timeout: 10 # the number of seconds allowed for one batch ingest call to kairosdb.
            use_compression: true # enable or disables the http transport compression.
```

The metrics will be pushed in KairosDB using the Rest API supported by the Kairos TSDB: https://kairosdb.github.io/docs/build/html/restapi/AddDataPoints.html
