### ISSUE TITLE
Missing field metricKind in stackdriver exporter

### ISSUE THREAD

**Issue by GoPavel** [census-instrumentation/opencensus-service#635]
When I am using ocagent for transport my prometheus metric to stackdriver, I see the following error:
```
2020/02/20 21:05:26 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = Request was missing field metricDescriptor.metricKind: The descriptor does not have the metric kind set.
```
Meanwhile, I find my metrics in gcloud console but I am not sure about completeness that metrics.

I try to check bug in proto file but I confused about different `MetricDescriptor` in [src/opencensus/proto/metrics/v1/metrics.proto](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto#L53) and in [google/api/metric.proto](https://github.com/googleapis/googleapis/blob/master/google/api/metric.proto#L33). 

My yaml config:
```yaml
log-level: DEBUG

receivers:
  jaeger:
    collector_thrift_port: 14267
    collector_http_port: 14268
    agent_compact_thrift_port: 6831

  prometheus:
    config:
      global:
        scrape_interval: 10s
        scrape_timeout: 5s
        external_labels:
          monitor: 'codelab-monitor'
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'my-service'
          static_configs:
            - targets: ['localhost:8000', 'localhost:8088']

exporters:
  stackdriver:
    project: "PROJECT"
    metric_prefix: "opencensus_demo"
    enable_tracing: false
    enable_metrics: true

```
