### ISSUE TITLE
Reconsider the config file layout

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-service#90]
Config file requires some hierarchal structure:

```
interceptors:
    opencensus: ...

exporters:
    zipkin: ...
    stackdriver: ....
```
